### ISSUE TITLE
Inquiry About the Choice of GPT-2 for Nuwa

### ISSUE THREAD

**Issue by zezhishao** [Chengyui/NuwaTS#1]
Hi Jinguo,

First of all, thank you for your excellent work on the Nuwa model 🎉. I have been carefully reading through the paper, and I have a question regarding the design choice of the model architecture.

As a model aimed at time series imputation, why did you choose GPT-2, which uses a Transformer Decoder (unidirectional self-attention) as the backbone network?

Wouldn't using a Transformer Encoder (bidirectional self-attention) be more beneficial for capturing the dependencies in both past and future time steps in time series data?

I would appreciate it if you could provide some insights or reasoning behind this architectural choice.

Thank you in advance for your time and consideration!

**Comment by zezhishao** [comment]
I noticed that the results in Table 11 show that Decoder models generally outperform Encoder models. 

However, intuitively, bidirectional context might be more helpful for achieving more accurate interpolation. Do you have a deeper insight or explanation for this result?

As I have limited understanding of time series interpolation, I would greatly appreciate your guidance!

**Comment by zezhishao** [comment]
I noticed that the results in Table 11 show that Decoder models generally outperform Encoder models. 

However, intuitively, bidirectional context might be more helpful for achieving more accurate interpolation.

Do you have a deeper insight or explanation for this result?

As I have limited understanding of time series imputation, I would greatly appreciate your guidance!

**Comment by Chengyui** [comment]
Thank you for your feedback!

Your main question revolves around why NuwaTS performs better using GPT2's causal attention compared to BERT's bidirectional attention.

There are two reasons for this:

Firstly, although GPT2's backbone employs casual attention, which may struggle to process the missing preceding segment, the flattening  head output layer plays a crucial role. By flattening all the final output hidden states and directly projecting them to imputed results, this output layer effectively acts in a bidirectional information mixer. This is because it has been trained under massive data, and as long as the hidden states of the latter segment carry rich semantic information from GPT2's backbone, it can also impute the preceding segment.

Secondly, time series inherently follow a causal structure from past to future, similar to natural language. OpenAI has observed that decoders tend to exhibit stronger scaling laws compared to encoders. Therefore, during extensive training on massive  data, casual attention is more beneficial than bidirectional attention.

**Comment by zezhishao** [comment]
Thank you for your prompt reply!
